### ISSUE TITLE
Searching for instance using related by without a foreign key 

### ISSUE THREAD

**Issue by zydsh** [zydsh/hrm#1]
Not clear how to select instances through a relationship using related by while in a class operation. Some reviewed examples used related by with 'self->', others use examples that don't work with class operation.

Work around: create a unique ID for Section instances that combine unique ID of a selected class Budget instance and class Chapter instance.

**Comment by johnrwolfe** [comment]
The 'self' keyword is invalid within a class-based operation, as it refers to the instance that is currently executing an instance-based activity (e.g., instance-based operation, instance-based state-entry activity, instance-based transition activity).  Since a class-based operation is invoked using only the class name, not an instance handle, there is no instance involved, hence the 'self' keyword is invalid within this context.
In order to use "select related by" from within a class-based operation, an instance handle must first be obtained.  For example:
select any carpark from instances of Carpark;
select one nextTicketRequest related by carpark->TicketRequest[R3.'will service next'];

**Comment by zydsh** [comment]
Thanks John,

I'm starting to understand the logic when manipulating large sums of data, you typically would have to have persistence, and thus would need to formalize and have foreign keys to select among one-to-many associations. 

In the example carpark instance you mentioned, you choose a carpark and through a one-to-one association from TicketRequest you get the ticket to be serviced. 

Using the same example, how can we extend it to R2.'has queued'? 
Thus selecting a specific ticket on queue.

**Comment by johnrwolfe** [comment]
### Persistence and Databases
Typically, I see persistence as satisfying a requirement for persisting data across invocations of a system, power cycles, etc.  But, most of my clients build embedded systems that have no need to manipulate large collections of data that cannot fit into the RAM provided by the system.  I think it is important for us to clarify our requirements for persistence.  We know that this system will require persistent storage of employee records, payroll, etc.  But, do you anticipate this system requiring the ability to manipulate collections of data that cannot be loaded into memory?
### Formalized Associations, Identifiers, and Foreign Keys
Separately, I would like to understand the connection you are making between persistence, formalized association, and selection with foreign keys.  At this point the persistence facility offered by Ciera works only with formalized associations, but this is a deficiency that can be rectified.  For the reasons mentioned [here](https://github.com/johnrwolfe/CarPark/issues/34) I  recommend avoiding formalizing associations, as it just adds clutter to the model.  Instead of using foreign keys to find instances of interest, it is much better to use associations.  Certainly, using an identifier to find an instance is necessary when receiving an identifier from outside the domain (Commence employee number 42), but within the domain, there should be very little, if any, use of identifiers or foreign keys to find specific instances as doing so hides an implicit association at the lowest level of the model, within an activity (select any...where) instead of exposing this important abstraction explicitly as an association at the highest level, the class model.
### Carpark Example
Regarding the carpark example, we are already _selecting a specific ticket request from the queue_.  That is precisely the purpose of R3.  You will notice that there is no attribute of TicketRequest, nextToBeServiced.  We could replace R3 with such a Boolean attribute and then use: 
`select any nextTicketRequest related by carpark->TicketRequest[R2.'has queued'] where ( selected.nextToBeServiced );`
But, I prefer to use the association (R3), as I think it is clearer, and does a better job of drawing the reader's attention to the semantics involved than using a Boolean flag on the TicketRequest class.
### Associations are Powerful
For a more interesting example of using associations to convey semantics on the class model while leveraging them within activities, please review the Carpark class model in the area of Stay, ChargeSegment, AdditionalChargeSegment, BaseChargeSegment, AdditionalCharge, and Charge.  Then, have a look at Stay::CalculateAdditionalCharge() and recognize how the subtypes are used to partition the instance population of ChargeSegment.  Specifically, notice:
`select many BaseChargeSegments related by self->ChargeSegment[R15]->
BaseChargeSegment[R32]->ChargeSegment[R32];`
which finds all instances of ChargeSegment related to a BaseChargeSegment.  In other words, this single line of OAL partitions the instance population of ChargeSegment to provide only those that are base charges as opposed to those that are the result of an overstay.

**Comment by zydsh** [comment]
Thanks John for the explanation.

1. **Associations as abstractions**:  It is now clear to me how 'relate by' works. It replaces the foreign key concept altogether, as it points to each instance through the association. Eventually, when the instances are collected it becomes a list to iterate on like any other list. The foreign key concept is then an implementation concern, and associations is an abstraction. 

2. **Manipulating a collection of data that cannot be loaded in memory**: As an enterprise system, as you know, the amount of data processed can be large that memory size and performance issues have to be considered. Furthermore, there is emphasis on manipulating data by creation, reading, updating, and deleting (CRUD), as you have noticed in the HRM. Thus, there is also concern about security because of the data intensive nature of such systems. Such systems are also distributed, which means the system is architected some way, typically layered and heterogeneous. 

So, should the compiler help in serving the CRUD concerns, or security concerns. I know there is a discussion around the role of model compilers in fitting with the application domain in (Mellor and Balcer, 2002), but I wonder in which direction the discussion have progressed?

**Comment by johnrwolfe** [comment]
### Associations as Abstractions
Precisely!
### Persistence, Memory Constraints
Every aspect mentioned in this section is application-independent.  Each of these represents an architectural, design, or implementation concern.  Our goal for the ERP models is to produce implementation-independent solutions focused on the subject matter of interest (e.g., HR, Finance, etc.).  As such, we must avoid mixing design and implementation artifacts (e.g., CRUD, serialization, etc.) into these implementation-independent application models.
### Where to Handle Implementation Concerns?
The short answer is, in the model compiler, but this obscures some of the realities of a system like the one we are building.  This topic requires a good deal of requirements clarification followed by exploration of existing technology.  I propose that we defer this aspect until after the pilot-project demonstration so that we can focus this initial demonstration on implementation-independent, executable models, and model compilation.  Helping our audience reach a sufficient level of understanding on these aspects of the approach requires time and effort, so I recommend avoiding the distraction of a discussion about persistence, virtual memory, security, distribution, etc. 

Once our partners have a shared appreciation for executable models and model compilation, it might then make sense to use a subsequent pilot project to demonstrate how various implementation concerns can be woven into or interfaced with code generated from the application models.

**Comment by zydsh** [comment]
This is very helpful, John. Perhaps more discussions will continue on future threads.
Thanks.
